[project]
name = "symmeplot"
version = "0.0.1"
authors = [
  { name="Timo Stienstra", email="timostienstra00@gmail.com" },
]
description = "SymPy Mechanics Plotter"
readme = "README.md"
requires-python = ">=3.10"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
"Homepage" = "https://github.com/TJStienstra/symmeplot"
"Bug Tracker" = "https://github.com/TJStienstra/symmeplot/issues"
"Documentation" = "https://tjstienstra.github.io/symmeplot/"

[tool.ruff]
target-version = "py37"
select = ["A", "B", "C", "D", "E", "F", "I", "N", "Q", "W", "NPY", "RUF", "SIM", "TID",
          "T20", "UP"]
ignore = ["A003", "C901", "D100", "D105", "D107", "D203", "D213"]
show-source = true

[tool.ruff.per-file-ignores]
"doc/conf.py" = ["A001"]  # Ignore copyright shadowing
"*/__init__.py" = ["D104"]
"symmeplot/tests/*" = ["D", "N806", "S101"]
"symmeplot/plot_artists.py" = ["D102"]

[tool.pytest.ini_options]
testpaths = [
    "symmeplot/tests",
]
