[tool.poetry]
name = "symmeplot"
version = "0.0.1"
description = "SymPy Mechanics Plotter"
authors = ["TJStienstra <timostienstra00@gmail.com>"]
readme = "README.md"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
[tool.poetry.group.lint.dependencies]
ruff = "^0.0.258"



[tool.poetry.group.test.dependencies]
pytest = "^7.2.2"


[tool.poetry.group.doc.dependencies]
sphinx = "^6.1.3"
sphinx-rtd-theme = "^1.2.0"
jupyter-sphinx = "^0.4.0"
autodocsumm = "^0.2.10"
ipykernel = "^6.22.0"

[project.urls]
"Homepage" = "https://github.com/TJStienstra/symmeplot"
"Bug Tracker" = "https://github.com/TJStienstra/symmeplot/issues"
"Documentation" = "https://tjstienstra.github.io/symmeplot/"

[tool.poetry.dependencies]
python = "^3.8"
sympy = "^1.11.1"
numpy = "^1.24.2"
matplotlib = "^3.7.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.ruff]
target-version = "py37"
select = ["A", "B", "C", "D", "E", "F", "I", "N", "Q", "W", "NPY", "RUF", "SIM", "TID",
          "T20", "UP"]
ignore = ["A003", "C901", "D100", "D105", "D107", "D203", "D213"]
show-source = true

[tool.ruff.per-file-ignores]
"doc/conf.py" = ["A001"]  # Ignore copyright shadowing
"*/__init__.py" = ["D104"]
"symmeplot/tests/*" = ["D", "N806", "S101"]
"symmeplot/plot_artists.py" = ["D102"]

[tool.pytest.ini_options]
testpaths = [
    "symmeplot/tests",
]
