# Based of: https://github.com/eeholmes/readthedoc-test
on:
  push:
    branches:
      - main

jobs:

  deploy_docs_job:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install pyqtgraph dependencies
        # https://pytest-qt.readthedocs.io/en/latest/troubleshooting.html#github-actions
        uses: tlambert03/setup-qt-libs@v1
      - name: Setup headless display
        uses: pyvista/setup-headless-display-action@v3
      - name: Install uv
        uses: astral-sh/setup-uv@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: "pyproject.toml"
      - name: Install dependencies
        run: uv sync --all-extras
      - name: make the sphinx docs
        run: |
          uv run make -C docs clean
          uv run make -C docs html
      - name: Init new repo in dist folder and commit generated files
        run: |
          cd docs/_build/html/
          git init
          touch .nojekyll
          git add -A
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git commit -m 'deploy'
      - name: Force push to destination branch
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
          force: true
          directory: ./docs/_build/html
