name: TestPyPI
on:
  push:
    branches:
      - main
jobs:
  test_pypi:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Install uv
      uses: astral-sh/setup-uv@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version-file: "pyproject.toml"
    - run: >-
        uv version patch &&
        version=$(uv version | awk '{print $2}') &&
        uv version $version.dev.$(date +%s)
    - run: uv build
    - uses: pypa/gh-action-pypi-publish@release/v1
      with:
        user: __token__
        password: ${{ secrets.TEST_PYPI_TOKEN }}
        repository-url: https://test.pypi.org/legacy/
