# Based of: https://github.com/eeholmes/readthedoc-test
on: [push, pull_request]

jobs:

  test_docs_job:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.10', '3.11']
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          pipx install flit
          flit install --extras all
      - name: make the sphinx docs
        run: |
          pytest
          make -C doc clean
          make -C doc html
