name: Tests

on:
  pull_request:
  push:
    branches:
      - main

jobs:

  #----------------------------------- code-quality -----------------------------------#

  code-quality:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: "pyproject.toml"
      - name: Install dependencies
        run: uv sync --all-extras
      - name: Lint check with ruff
        run: uv run ruff check .
      - name: Lint format with ruff
        run: uv run ruff format . --check

  #-------------------------------------- tests ---------------------------------------#

  tests:
    needs: code-quality

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.9', '3.10', '3.11', '3.12']
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install pyqtgraph dependencies
        # https://pytest-qt.readthedocs.io/en/latest/troubleshooting.html#github-actions
        uses: tlambert03/setup-qt-libs@v1
      - name: Setup headless display
        uses: pyvista/setup-headless-display-action@v3
      - name: Install uv
        uses: astral-sh/setup-uv@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: uv sync --all-extras
      - name: Run tests
        run: uv run pytest

  test_sympy_dev:
    needs: code-quality

    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install pyqtgraph dependencies
        # https://pytest-qt.readthedocs.io/en/latest/troubleshooting.html#github-actions
        uses: tlambert03/setup-qt-libs@v1
      - name: Setup headless display
        uses: pyvista/setup-headless-display-action@v3
      - name: Install uv
        uses: astral-sh/setup-uv@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: "pyproject.toml"
      - name: Install dependencies
        run: uv sync --all-extras
      - name: Install dependencies
        run: |
          uv sync --all-extras
          uv pip uninstall sympy
          uv pip install git+https://github.com/sympy/sympy.git
      - name: Run tests
        run: uv run pytest

  #------------------------------------ docs-tests ------------------------------------#

  test_docs_job:
    needs: code-quality

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.9', '3.10', '3.11', '3.12']
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install pyqtgraph dependencies
        # https://pytest-qt.readthedocs.io/en/latest/troubleshooting.html#github-actions
        uses: tlambert03/setup-qt-libs@v1
      - name: Setup headless display
        uses: pyvista/setup-headless-display-action@v3
      - name: Install uv
        uses: astral-sh/setup-uv@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: uv sync --all-extras
      - name: make the sphinx docs
        run: |
          uv run make -C docs clean
          uv run make -C docs html
